### ISSUE TITLE
How to registry a custom renderer

### ISSUE THREAD

**Issue by chenghsuan** [handsontable/vue-handsontable-official#52] opened 2018-05-31 07:25 UTC
Hi there~
I have a problem that how to registry the custom renderer with HotTable?
If use HandsonTable.js can use following to deal with 
`Handsontable.renderers.registerRenderer('asterix', asterixDecoratorRenderer);`

Is there any way to handle custom renderer?

**Comment by AMBudnik** [comment] 2018-06-21 11:55
Hi 

here's https://github.com/handsontable/vue-handsontable-official/issues/27 a topic with demos for custom renderers

**Comment by mrpiotr-dev** [comment] 2018-06-22 10:12
Duplicate of #27

**Closed as completed by mrpiotr-dev** 2018-06-22 10:12 UTC
Labels: Status: Answered
