### ISSUE TITLE
Build fails on demo found in README

### ISSUE THREAD

**Issue by mekhami** [handsontable/vue-handsontable-official#8] opened 2017-08-02 23:09 UTC
Here's my code:

```
<template>
  <div id="view-panel">
    <h1>View Panel</h1>
    <HotTable :root="root" :settings="hotSettings"/>
  </div>
</template>

<script>
import HotTable from 'vue-handsontable-official'

export default {
  name: 'Results',
  components: { HotTable },
  props: ['resourceList'],
  data () {
    return {
      root: 'test-hot',
      hotSettings: {
        data: this.resourceList,
        colHeaders: true
      }
    }
  }
}
</script>

<style>
#test-hot {
  width: 600px;
  height: 400px;
  overflow: hidden;
}
</style>
```
Here's my package.json: 

```
{
  "name": "sample_frontend",
  "description": "A Vue.js project",
  "version": "1.0.0",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "apollo-client": "^1.9.0-1",
    "graphql-tag": "^2.4.2",
    "vue": "^2.3.3",
    "vue-apollo": "^2.1.0-beta.20",
    "vue-handsontable-official": "^1.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-env": "^1.5.1",
    "babel-preset-es2015": "^6.24.1",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "node-sass": "^4.5.0",
    "sass-loader": "^5.0.1",
    "vue-loader": "^12.1.0",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  }
}
```

Here's my webpack config (generated by vue-cli):
```
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './static/js'),
    publicPath: '/static/js/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            // Since sass-loader (weirdly) has SCSS as its default parse mode, we map
            // the "scss" and "sass" values for the lang attribute to the right configs here.
            // other preprocessors should work out of the box, no loader config like this necessary.
            'scss': 'vue-style-loader!css-loader!sass-loader',
            'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
    }
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}
```
When I build my project, I get the following error: 

```
ERROR in build.js from UglifyJs
Unexpected token: name (SettingsMapper) [./~/vue-handsontable-official/src/settingsMapper.js:3,0][build.js:68783,6]
```

What am I missing?

**Comment by mekhami** [comment] 2017-08-02 23:42
So it seems that vue-handsontable-official is not doing its own transpiling. Why is this? The transpile should absolutely be handled by the build process here so that Uglify can receive ES5 code from node_modules.

Is this a conscious decision or an oversight?

**Comment by krimes** [comment] 2017-09-11 13:33
Hi @mekhami 
I too have experienced this problem. And her decision was to move the library to a folder not located in the `node_modules`. And writing 
```
resolve: {
  alias: {
    'vue-handsontable-official': path.resolve(__dirname, 'libs/vue-handsontable-official'),
  }
}
```
Most likely the problem is in the configuration of Webpack:
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
```
Should
```
      {
        test: /\.js$/,
        loader: 'babel-loader'
      },
```

**Comment by JakeAlmer** [comment] 2017-11-01 18:21
getting the same problem, you guys find a solution?

**Comment by eard7** [comment] 2017-11-05 07:31
@JakeAlmer i had the same problem, but solved it.
I am assuming you are using webpack. You need to install the latest version of uglifyjs-webpack-plugin with
`npm i -D uglifyjs-webpack-plugin`

Then in your webpack config add this at the top of the file (in my case the file was webpack.prod.conf.js)
`var UglifyJSPlugin = require('uglifyjs-webpack-plugin')`

And then find and replace this
`new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),`

With this
`new UglifyJSPlugin({
      sourceMap: true
    }),`

The reason of this problem is that webpack use an old version of uglifyjs-webpack-plugin that doesn't support es6. The latest version of uglifyjs-webpack-plugin support es6 :)

Hope this helps!

**Comment by timvisee** [comment] 2018-02-23 13:07
After applying these changes, this error still shows up in my configuration (in a personal project).
I'm running `vue-handsontable-official` version `1.1.0`.

Edit: I was able to solve it using the change in this post instead: https://github.com/handsontable/vue-handsontable-official/issues/36#issuecomment-361877334

**Comment by jansiegel** [comment] 2018-03-30 09:03
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment] 2018-05-14 12:59
I think we can close this issue.
Feel free to reopen if you find the same bug in v2.0.0-beta1+

**Closed as completed by mrpiotr-dev** 2018-05-14 12:59 UTC
