### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by alexon1234** [handsontable/vue-handsontable-official#20] opened 2017-11-06 11:57 UTC
@handsontable
I am trying to use the undo method but I dont know how to make it work in vue handsontable.
I have seen the demo like this one http://jsfiddle.net/s6t768pq/609/ where by default comes enabled.

I try on vue to enable by default, but i can not make it work. Anyone have been able to make it work?

```
<HotTable ref="testHot"
                :root="root" 
                :settings="hotSettings"
                :columns="columns"
                :data="dataTable"
                :colHeaders="columnHeaders"
                :readOnly="readOnly"
                :rowHeaders="true"
                :contextMenu="true"
                :manualColumnMove="true"
                :manualRowMove="true"
                :dropdownMenu="true"		
                :mergeCells="true"
                :columnSorting="true"
                :manualColumnResize="true"
                :manualRowResize="true"
                :formulas="true"
                :undo ="true"
                :onAfterCreateRow="afterCreateRowHandler"
                :onAfterChange="afterChangeHandler"
                :filters="true"
            ></HotTable>
```

PS. If I check the component I have  ```undo=true``` , but ```isUndoAvailable() = false```, do I have to enable the plugin?

**Comment by samertm** [comment] 2017-11-09 04:36
I ran into this problem too. When I looked into it, I found that the problem was caused by something emitting a 'loadData' event every time you update a cell, and the undo plugin listens for events in onAfterChange and clears the undo plugin if it sees a 'loadData' event.

This plugin emits a loadData event for every edit because it calls `this.table.updateSettings` in updateHotSettings and updateBulkHotSettings. If you comment that line out, undo works fine (and so does everything else).

The reason this works when your data is a nested array is because vue doesn't watch arrays for changes, so updateHotSettings doesn't get called at all.

One potential fix for updateHotSettings is to not call updateSettings when `updatedProperty` is data. I'm going to try and get something working locally that does that.

**Comment by alexon1234** [comment] 2017-11-09 08:31
Thanks for the information. I will check your solution

**Comment by alexon1234** [comment] 2017-11-09 21:47
It worked, but I think depends how you use Handontable, you will lose the reactivite and you will be force then to call manually to `updateSettings ` when you needed

**Comment by Gaga86** [comment] 2017-12-04 18:18
I think I found the "root" of the bug and a temporary fix to the problem above.
In the file:
/node_modules/handsontable/dist/handsontable.js
near the end of this.loadData function is the following code:
`if (priv.firstRun) {
      priv.firstRun = [null, 'loadData'];
    } else {
      instance.runHooks('afterChange', null, 'loadData');
      instance.render();
    }`

When afterChange hook is called, the third argument ("load data") is what's passed as the source.
if you delete that third argument, undo/redo works fine without the need to manually update settings as @alexon1234 stated.
So the code should look like this:
`if (priv.firstRun) {
      priv.firstRun = [null, 'loadData'];
    } else {
      instance.runHooks('afterChange', null);
      instance.render();
    }`

**Important note:**
I noticed that when you change something in the table, afterChange from the your-handsontable.vue file is called two times. First time with the source value of "edit", and second time (before the quick fix above) with the source value of "loadData" (that is responsible for removing the undo functionality).
After you edit the line in the else statement as above, the afterChange is also called two times, but this time instead of "loadData" source on the second function call, the source is undefined, and that is why undo/redo is working properly.
Hope this helps somebody.

**Comment by gurvancampion** [comment] 2018-05-01 18:16
Up!
Having the same issue but I can't modify directly in the node_modules files in my project.
I have tried to override the function "loadData" but I didn't managed to find a solution.
Maybe it is possible to fix this problem with the quick fix above mentioned by @Gaga86 ?

**Comment by mrpiotr-dev** [comment] 2018-05-14 14:41
Hi @alexon1234,
I think we have to fix #50 first.

At this moment I left label "bug". We have to verify it after fix #50.

**Comment by jansiegel** [comment] 2018-09-14 10:25
Should be fixed in #74

**Comment by jansiegel** [comment] 2018-09-25 08:56
This should work fine in `@handsontable/vue` `3.0.0`.

**Closed as completed by jansiegel** 2018-09-25 08:56 UTC
Labels: Type: Bug

**Comment by TeamDman** [comment] 2020-05-15 18:31
I'm using a handsontable with v-once and a computed property for the data object.
I'm manually calling loadData in a watcher on my computed property.
The undo wasn't working, since it clears its history when loadData is called.
To fix this:
``` js
	watch: {
		projectTable() { // my computed property
			if (!this.$refs.myTable) return; // not mounted yet!!!
			const undoRedo = this.$refs.myTable.hotInstance.undoRedo;

			// clone with spread
			// undoRedo plugin clears history by setting .length=0
			// we want to make sure our clone is preserved properly
			const doneActions = [...undoRedo.doneActions];
			const undoneActions = [...undoRedo.undoneActions];

			this.$refs.myTable.hotInstance.loadData(this.projectTable);
			// loadData event is fired, undoRedo now clears its history

			this.$nextTick(() => {
				// next render tick, restore the history
				undoRedo.doneActions = doneActions;
				undoRedo.undoneActions = undoneActions;
			});
		},
	},
```

https://github.com/handsontable/handsontable/blob/73825c299b65387b63991d3e263f964b71767f33/src/plugins/undoRedo/undoRedo.js#L258-L261

**Comment by pnowak** [comment] 2020-05-18 11:25
Hi @TeamDman 

Can you show your implementation?

May I send to you demo from our docs - https://codesandbox.io/s/advanced-vue-hot-column-implementation-722-411-d4ymm?from-embed=&file=/src/main.js
And you based on it extend to better reflect your needs and your issue.

**Comment by TeamDman** [comment] 2020-05-19 13:33
I've modified your link to demonstrate the issue, this time using v-model instead of manually calling loadData the way I was on my project.

https://codesandbox.io/s/advanced-vue-hot-column-implementation-722-411-yubc2?file=/src/App.vue

Steps:
1. make a change
2. check the checkbox to enable the history hack
3. make another change
4. Ctrl+z/history will only work for changes made while the hack is and was still enabled

**Comment by pnowak** [comment] 2020-05-22 06:13
Hi @TeamDman 

I asked for consultancy our Vue developer.

I will come back with his comments as soon as possible.
